services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: opengmao
      POSTGRES_PASSWORD: opengmao
      POSTGRES_DB: opengmao
    ports:
      - "5432:5432"
    volumes:
      - opengmao_postgres:/var/lib/postgresql/data

volumes:
  opengmao_postgres:
