export const PRIMARY_NAVIGATION = [
  { href: "/", label: "Dashboard" },
  { href: "/search", label: "Search" },
  { href: "/notifications", label: "Notifications" },
  { href: "/assets", label: "Assets" },
  { href: "/assets/scan", label: "Scan QR" },
  { href: "/maintenance", label: "Maintenance" },
  { href: "/maintenance/my-work", label: "My work" },
  { href: "/maintenance/kanban", label: "Kanban" },
  { href: "/maintenance/calendar", label: "Calendar" },
  { href: "/maintenance/workload", label: "Workload" },
  { href: "/analytics/backlog", label: "Analytics" },
  { href: "/analytics/pm-compliance", label: "PM compliance" },
  { href: "/analytics/reliability", label: "Reliability" },
  { href: "/analytics/downtime", label: "Downtime" },
  { href: "/analytics/failure-pareto", label: "Failure Pareto" },
  { href: "/analytics/labor-utilization", label: "Labor" },
  { href: "/documents", label: "Documents" },
  { href: "/inventory", label: "Inventory" },
  { href: "/quality", label: "Quality" },
] as const;
