"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";

type AssetOption = { id: string; code: string; name: string };
type PmCompliance = {
  due: number;
  completedOnTime: number;
  completedLate: number;
  openOverdue: number;
  missed: number;
  complianceRate: number | null;
  empty: boolean;
  from: string;
  to: string;
  generatedAt: string;
};

type ApiResponse = {
  data?: PmCompliance;
  error?: { message?: string };
};

export default function PmComplianceClient({
  organizationId,
  siteId,
  assets,
  timeZone,
  initialFromDay,
  initialThroughDay,
}: {
  organizationId: string;
  siteId: string;
  assets: AssetOption[];
  timeZone: string;
  initialFromDay: string;
  initialThroughDay: string;
}) {
  const [fromDay, setFromDay] = useState(initialFromDay);
  const [throughDay, setThroughDay] = useState(initialThroughDay);
  const [assetId, setAssetId] = useState("");
  const [data, setData] = useState<PmCompliance | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const params = new URLSearchParams({
        organizationId,
        siteId,
        from: fromDay,
        to: throughDay,
      });
      if (assetId) params.set("assetId", assetId);

      const response = await fetch(`/api/analytics/pm-compliance?${params.toString()}`, {
        cache: "no-store",
      });
      const body = (await response.json()) as ApiResponse;
      if (!response.ok || !body.data) {
        throw new Error(body.error?.message ?? "Unable to load PM compliance");
      }
      setData(body.data);
    } catch (cause) {
      setData(null);
      setError(cause instanceof Error ? cause.message : "Unable to load PM compliance");
    } finally {
      setLoading(false);
    }
  }, [assetId, fromDay, organizationId, siteId, throughDay]);

  useEffect(() => {
    void load();
  }, [load]);

  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    void load();
  }

  return (
    <>
      <section className="card">
        <form onSubmit={submit} style={{ display: "flex", flexWrap: "wrap", gap: 12, alignItems: "end" }}>
          <label>
            <span className="muted">From ({timeZone})</span>
            <input type="date" value={fromDay} onChange={(event) => setFromDay(event.target.value)} required />
          </label>
          <label>
            <span className="muted">Through ({timeZone})</span>
            <input type="date" value={throughDay} onChange={(event) => setThroughDay(event.target.value)} required />
          </label>
          <label>
            <span className="muted">Asset</span>
            <select value={assetId} onChange={(event) => setAssetId(event.target.value)}>
              <option value="">All assets</option>
              {assets.map((asset) => (
                <option key={asset.id} value={asset.id}>{asset.code} · {asset.name}</option>
              ))}
            </select>
          </label>
          <button type="submit" disabled={loading}>{loading ? "Refreshing…" : "Apply"}</button>
        </form>
        <p className="muted" style={{ marginBottom: 0 }}>
          Definition: non-cancelled preventive work orders generated by the maintenance scheduler and due on the selected local calendar dates. Future due dates are excluded. A PM is compliant only when completed on or before its due date.
        </p>
      </section>

      {error ? <section className="card" role="alert">{error}</section> : null}

      {data ? (
        <>
          <div className="grid grid-4 section">
            <section className="card"><div className="muted">PM due</div><div className="title">{data.due}</div></section>
            <section className="card"><div className="muted">Compliance</div><div className="title">{data.complianceRate === null ? "—" : `${data.complianceRate.toFixed(1)}%`}</div></section>
            <section className="card"><div className="muted">Completed on time</div><div className="title">{data.completedOnTime}</div></section>
            <section className="card"><div className="muted">Missed</div><div className="title">{data.missed}</div></section>
          </div>

          <div className="grid grid-2 section">
            <section className="card">
              <h2>Outcome detail</h2>
              {data.empty ? (
                <p className="muted">No scheduled preventive work orders were due in this reporting window.</p>
              ) : (
                <dl className="detail-list">
                  <div><dt>Completed late</dt><dd>{data.completedLate}</dd></div>
                  <div><dt>Still open after due date</dt><dd>{data.openOverdue}</dd></div>
                </dl>
              )}
            </section>
            <section className="card">
              <h2>Resolved reporting window</h2>
              <dl className="detail-list">
                <div><dt>From</dt><dd>{data.from}</dd></div>
                <div><dt>To (exclusive)</dt><dd>{data.to}</dd></div>
                <div><dt>Timezone</dt><dd>{timeZone}</dd></div>
                <div><dt>Generated</dt><dd>{data.generatedAt}</dd></div>
              </dl>
            </section>
          </div>
        </>
      ) : null}
    </>
  );
}
